language: csharp
solution: MagicBot.sln
mono: none
dotnet: 2.2
script:
  - dotnet restore
install:
  - sudo apt-get install nunit-console
  #- nuget restore MagicBot.sln
  
script:
  - xbuild /p:Configuration=Release MagicBot.sln
  #- nunit-console ./MagicBot.Model.Tests/bin/x64/Release/netcoreapp2.2/MagicBot.Model.Tests.dll
